package server

import (
	"bytes"
	"testing"
	"time"

	"github.com/japharyroman/fuelgrid-os/internal/reporting"
)

// sampleEnvelope builds a representative rendered ReportEnvelope exercising every
// premium-PDF block: KPIs (money + count), a multi-column table with numeric and
// text columns, insights of varying severity, data-quality caveats, and
// recommended actions. Money values are exact decimal strings.
func sampleEnvelope() ReportEnvelope {
	sid := "11111111-1111-1111-1111-111111111111"
	env := newEnvelope("station-close", "Daily Station Close — Mikocheni", "2026-05", &sid)
	env.FiltersUsed["station_id"] = sid
	env.FiltersUsed["period"] = "2026-05"
	env.Summary = []summaryMetric{
		{Label: "Sales value", Value: "12345678.90", Unit: "TZS"},
		{Label: "Net revenue", Value: "11000000.00", Unit: "TZS"},
		{Label: "Margin", Value: "987654.32", Unit: "TZS"},
		{Label: "Total tendered", Value: "12000000.00", Unit: "TZS"},
		{Label: "Cash variance", Value: "-1500.00", Unit: "TZS"},
		{Label: "Open exceptions", Value: "2", Unit: "count"},
	}
	env.Table.Columns = []string{"business_date", "status", "gross", "net", "margin", "tendered", "cash_variance"}
	env.Table.Rows = [][]string{
		{"2026-05-30", "locked", "12345678.90", "11000000.00", "987654.32", "12000000.00", "-1500.00"},
		{"2026-05-29", "locked", "11111111.10", "10000000.00", "900000.00", "11050000.00", "250.00"},
	}
	env.Insights = []reporting.Insight{
		{Severity: reporting.SeverityWarning, Message: "Cash variance exceeded tolerance on the latest day.", RecommendedAction: "Recount the drawer and reconcile the shortfall."},
		{Severity: reporting.SeverityInfo, Message: "Snapshot covers 2 recent revenue days."},
	}
	env.DataQuality = []dataQualityItem{
		{Level: "warning", Message: "One shift remained unclosed when this report was generated."},
	}
	env.RecommendedActions = []string{"Recount the drawer and reconcile the shortfall."}
	return env
}

// TestPremiumPDF_BrandingAbsent renders the premium envelope PDF with the EMPTY
// (FuelGrid-only) letterhead — the common path when a tenant has no
// tenant_branding row — and asserts it renders without panic into a valid PDF.
func TestPremiumPDF_BrandingAbsent(t *testing.T) {
	at := time.Date(2026, 6, 14, 9, 30, 0, 0, time.UTC)
	out, err := renderEnvelopePDF(sampleEnvelope(), LetterheadBranding{}, "Ada Admin", at)
	if err != nil {
		t.Fatalf("renderEnvelopePDF (no branding): %v", err)
	}
	assertValidPDF(t, out)
}

// TestPremiumPDF_BrandingPresent renders with a full text letterhead (no logo
// bytes, so the helper exercises the text-block branding path) and asserts a
// valid PDF. A real logo would require embedding image bytes; the text branding
// path is the determinism-relevant one and is covered here.
func TestPremiumPDF_BrandingPresent(t *testing.T) {
	at := time.Date(2026, 6, 14, 9, 30, 0, 0, time.UTC)
	branding := LetterheadBranding{
		DisplayName:    "Mikocheni Energy Ltd",
		LegalName:      "Mikocheni Energy Limited",
		TaxID:          "123-456-789",
		RegistrationNo: "RC-2026-0001",
		AddressLine1:   "12 Bagamoyo Road",
		City:           "Dar es Salaam",
		Country:        "Tanzania",
		Phone:          "+255 22 000 0000",
		Email:          "ops@mikocheni.co.tz",
		Website:        "mikocheni.co.tz",
		FooterNote:     "Generated by FuelGrid OS",
	}
	out, err := renderEnvelopePDF(sampleEnvelope(), branding, "Ada Admin", at)
	if err != nil {
		t.Fatalf("renderEnvelopePDF (branding): %v", err)
	}
	assertValidPDF(t, out)
}

// TestPremiumPDF_EmptyEnvelope renders a minimal (no summary, no table, no
// insights) envelope and asserts the layout still produces a valid PDF rather
// than panicking on the empty blocks.
func TestPremiumPDF_EmptyEnvelope(t *testing.T) {
	env := newEnvelope("financials", "Financial Statement", "this-month", nil)
	out, err := renderEnvelopePDF(env, LetterheadBranding{}, "", time.Time{})
	if err != nil {
		t.Fatalf("renderEnvelopePDF (empty): %v", err)
	}
	assertValidPDF(t, out)
}

// TestPremiumPDF_DeterministicForSameInput renders the same envelope twice with a
// pinned generatedAt and asserts byte-identical output — the document is
// deterministic, so the audited checksum is stable for a given report snapshot.
func TestPremiumPDF_DeterministicForSameInput(t *testing.T) {
	at := time.Date(2026, 6, 14, 9, 30, 0, 0, time.UTC)
	a, err := renderEnvelopePDF(sampleEnvelope(), LetterheadBranding{}, "Ada Admin", at)
	if err != nil {
		t.Fatalf("render a: %v", err)
	}
	b, err := renderEnvelopePDF(sampleEnvelope(), LetterheadBranding{}, "Ada Admin", at)
	if err != nil {
		t.Fatalf("render b: %v", err)
	}
	if !bytes.Equal(a, b) {
		t.Fatal("premium PDF is not deterministic for identical input")
	}
}

// TestRenderEnvelopeCSV_CarriesDecimalStrings asserts the CSV renderer passes the
// exact decimal money strings through verbatim (no float reformatting).
func TestRenderEnvelopeCSV_CarriesDecimalStrings(t *testing.T) {
	out := string(renderEnvelopeCSV(sampleEnvelope()))
	for _, want := range []string{"12345678.90", "-1500.00", "987654.32", "Daily Station Close"} {
		if !contains(out, want) {
			t.Fatalf("CSV missing exact value %q\n%s", want, out)
		}
	}
}

// contains is a tiny strings.Contains shim kept local to avoid widening imports.
func contains(haystack, needle string) bool {
	return bytes.Contains([]byte(haystack), []byte(needle))
}
